
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'abre_chave abre_colchete abre_parentese atrib bin chave_valor exec fecha_chave fecha_colchete fecha_parentese id imprimir ne num porta_log sinal tv virgulastart : expression\n             | emptyexpression : impressao\n                  | atribuicaoempty :impressao : imprimir abre_parentese num fecha_parentese \n                | imprimir abre_parentese id fecha_parenteseatribuicao : sinal id atrib num'
    
_lr_action_items = {'$end':([0,1,2,3,4,5,13,14,15,],[-5,0,-1,-2,-3,-4,-6,-7,-8,]),'imprimir':([0,],[6,]),'sinal':([0,],[7,]),'abre_parentese':([6,],[8,]),'id':([7,8,],[9,11,]),'num':([8,12,],[10,15,]),'atrib':([9,],[12,]),'fecha_parentese':([10,11,],[13,14,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'start':([0,],[1,]),'expression':([0,],[2,]),'empty':([0,],[3,]),'impressao':([0,],[4,]),'atribuicao':([0,],[5,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> start","S'",1,None,None,None),
  ('start -> expression','start',1,'p_start','yacc.py',8),
  ('start -> empty','start',1,'p_start','yacc.py',9),
  ('expression -> impressao','expression',1,'p_expression','yacc.py',13),
  ('expression -> atribuicao','expression',1,'p_expression','yacc.py',14),
  ('empty -> <empty>','empty',0,'p_empty','yacc.py',18),
  ('impressao -> imprimir abre_parentese num fecha_parentese','impressao',4,'p_impressao','yacc.py',22),
  ('impressao -> imprimir abre_parentese id fecha_parentese','impressao',4,'p_impressao','yacc.py',23),
  ('atribuicao -> sinal id atrib num','atribuicao',4,'p_atribuicao','yacc.py',27),
]
